### ISSUE TITLE
第六周第五章课后作业

### ISSUE THREAD

**Issue by KevinLuR** [sadDarkHorse/SCUT-Python-Course#1]
【1】 (程序设计)设计一个函数 func(a)，它接受一个正整数a，函数返回这个数字每个位上数字的和（函数内不能有input,print语句，不能使用global语句），例如，func(123)，返回6，因为1+2+3=6。
def func(a):
    sum = 0
    while a:
        sum += (a%10)
        a = a//10
    return sum
a = int(input('请输入一个整数:'))
print('它的各位数字和为{}'.format(func(a)))

【2】 (程序设计)定义函数def GetRandomChar()，返回一个随机的数字或大写或小写字母，每个符号出现的机会相等。然后调用该函数8次，生成并输出一个8位的验证码。
--

import random
def GetRandomChar():
    j = int(random.randint(0,61)) 
    if j<10:
        s = str(j)
    elif j<36:
        s = chr(ord("a")+j-10)
    else:
        s = chr(ord("A")+j-36)
    return s
s = ""
for i in range(8):
    s=s+GetRandomChar()
print("验证码为{}".format(s))
![image](https://user-images.githubusercontent.com/82448015/114555800-a1e57c00-9c9a-11eb-9ed3-c6b9c0fa0b94.png)
def DrawPic(n,char):
    for i in range(n):
        single1=char+char*(2*i)
        print(" "*(n-(i+1)),end="")
        print("{0:^}".format(single1))
    for i in range(n):
        if i != 0:
            print(" "*i,end="")
            single2=char+char*2*(n-1-i)
            print("{0:^}".format(single2))
n=int(input("请输入一个整数："))
char=input("请输入一个字符：")
DrawPic(n,char)

【4】 (程序设计)区间素数和。输入两个正整数m,n ( m < n)，编写程序求[m,n]之间的所有素数的和。要求定义函数def IsPrime(m)判断整数m是否是素数，如果是素数返回True否则返回False。
--

def isPrime(num):
    num=int(num)
    for i in range(2,num):
        if num%i==0 :
            return False
    if(num!=1):
        return True
def sum(a,b):
    sum=0
    for i in range(a,b+1):
        if isPrime(i):
            sum+=i
    return sum
m,n=input().split()
m=int(m)
n=int(n)
print('{:d}'.format(sum(m,n)))

【5】 (程序设计)一类完全平方数。输入正整数a,b，统计并输出[a,b]内有多少个数满足（1）是完全平方数（2）至少有两个数字相同。要求定义两个个函数：（1）判断是否是完全平方数的函数 def IsPerfectSquare(n)，当n是完全平方数时返回True，否则返回False（2）判断是否有相同数字的函数 def IsSameDigit(n) ，当n有相同数字时返回True，否则返回False
def IsPerfectSquare(n):
    a=int(pow(n,1/2))
    if a*a==n:
        return True
    else:
        return False
def IsSameDigit(n):
    a=str(n)
    b=list(a)
    new=[]
    for i in b:
        if i not in new:
            new.append(i)
    if len(b)==len(new):
        return False
    else:
        return True
a=int(input("请输入整数a:"))
b=int(input("请输入整数b:"))
S=0
for m in range(a,b+1):
    if IsPerfectSquare(m):
        if IsSameDigit(m):
            S+=1
print("在[{0},{1}]共有{2}个数满足条件".format(a,b,S))
--

**Comment by sadDarkHorse** [comment]
#2
